version: '3.8'
services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=finance_manager_db'
    ports:
      - '27017:27017'

  spring-app:
    build:
      context: ./
    ports:
      - '8082:8082'
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/finance_manager_db
